name: Run Template Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest, windows-latest]
        go-version: [1.13.x]
        node-version: [10.x]
        python-version: [3.7]
        dotnet: ['3.1.100']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install DotNet ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Deps
        run: |
          pip3 install pyenv-win
          pip3 install pipenv
      - name: Set Build Env Vars
        uses: allenevans/set-env@v1.0.0
        with:
          PULUMI_TEST_OWNER: "moolumi"
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          BLACK_LISTED_TESTS: "aws,linode,gcp,alicloud,azure,digitalocean,kubernetes,openstack,packet"
          #BLACK_LISTED_TESTS: "go,alicloud,azure,digitalocean,kubernetes,openstack,packet"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Pulumi GO SDK
        run: go get github.com/pulumi/pulumi-gcp/sdk/go/...
      - if: contains(matrix.platform, 'macOS') || contains(matrix.platform, 'ubuntu')
        name: Get dependencies non-windows
        run: make ensure
      - if: contains(matrix.platform, 'windows')
        name: Get dependencies windows
        run: |
          cd tests
          set GO111MODULE=on
          go mod tidy
          go mod vendor
      - if: contains(matrix.platform, 'macOS') || contains(matrix.platform, 'ubuntu')
        name: Run tests non-windows
        run: |
          make test_templates
      - if: contains(matrix.platform, 'windows')
        name: Run tests windows
        run: |
          cd tests
          go test -v -count=1 -cover -timeout 1h -parallel 10 .
